version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # Habilita la entrada estándar
    tty: true        # Mantiene la terminal abierta

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    stdin_open: true # Habilita la entrada estándar
    tty: true        # Mantiene la terminal abierta

  db:
    image: mysql:8.0
    container_name: reservapp_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reservapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
